'use client'
import { useRouter } from 'next/navigation'
import Navbar from './components/Navbar/Navbar'
import ProtectedRoute from './components/ProtectedRoute/ProtectedRoute'
import Sidebar from './components/SideBar/Sidebar'
import { AuthContextProvider } from './components/context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'IMS - Inventory Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = useRouter();

  return (
    <html lang="en">

      <body className={inter.className} style={{ overflow: 'hidden' }}>
        <AuthContextProvider>
          <ProtectedRoute router={router}>

            <Navbar />
            {children}
          </ProtectedRoute>

        </AuthContextProvider>
      </body>
    </html>
  )
}
