'use client'
import { useRouter } from 'next/navigation'
import Navbar from './components/Navbar/Navbar'
import ProtectedRoute from './components/ProtectedRoute/ProtectedRoute'
import Sidebar from './components/SideBar/Sidebar'
import { AuthContextProvider } from './context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'
import { InvoiceContextProvider } from './context/InvoiceContext'
import 'react-toastify/dist/ReactToastify.css';
import { TimeIntervalContextProvider } from './context/TimeIntervalContext'
import SidebarPro from './components/SideBar/Sidebar'
import SidebarContextProvider from './context/SidebarContext'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'IMS - Inventory Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = useRouter();


  return (
    <html lang="en">

      <body className={inter.className}>
        <AuthContextProvider>
          <SidebarContextProvider>
            <TimeIntervalContextProvider>
              <InvoiceContextProvider>
                <ProtectedRoute router={router}>
                  <div className="drawer lg:drawer-open">
                    <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
                    <div className="drawer-content flex flex-col items-center justify-center">
                      {/* Page content here */}

                      <Navbar />
                      {children}
                    </div>
                    <div className="drawer-side">
                      <label htmlFor="my-drawer-2" aria-label="close sidebar" className="drawer-overlay"></label>
                      <ul className="menu p-4 w-80 min-h-full bg-secondary  text-accent">
                        <Sidebar />
                      </ul>

                    </div>
                  </div>
                </ProtectedRoute>
              </InvoiceContextProvider>
            </TimeIntervalContextProvider>
          </SidebarContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
