'use client'
import { useRouter } from 'next/navigation'
import Navbar from './components/Navbar/Navbar'
import ProtectedRoute from './components/ProtectedRoute/ProtectedRoute'
import Sidebar from './components/SideBar/Sidebar'
import { AuthContextProvider } from './components/context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'
import { InvoiceContextProvider } from './components/context/InvoiceContext'
import 'react-toastify/dist/ReactToastify.css';
import { TimeIntervalContextProvider } from './components/context/TimeIntervalContext'
import SidebarPro from './components/SideBar/Sidebar'
import SidebarContextProvider from './components/context/SidebarContext'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'IMS - Inventory Management System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = useRouter();


  return (
    <html lang="en">

      <body className={inter.className}>
        <AuthContextProvider>
          <SidebarContextProvider>
            <TimeIntervalContextProvider>
              <InvoiceContextProvider>
                <ProtectedRoute router={router}>
                  <div className="grid grid-cols-[auto,1fr] h-screen">
                    <SidebarPro />
                    <div className="col-span-1 overflow-auto">
                      <Navbar />
                      {children}
                    </div>
                  </div>
                </ProtectedRoute>
              </InvoiceContextProvider>
            </TimeIntervalContextProvider>
          </SidebarContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
